[package]
name = "substrate-runtimes-fuzzers"
version = "0.1.0"
edition = "2021"
publish = false

[workspace]
resolver = "2"
members = [
    "kusama",
    "asset-hub-kusama",
    "coretime-kusama",
    "polkadot",
]